spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: niu_123456
    url: jdbc:mysql://cdb-4cc35yyq.cd.tencentcdb.com:10031/NERCMS?characterEncoding=utf-8&useSSL=false
    hikari:
      max-lifetime: 6000
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    database: 0
    jedis:
      pool:
        max-active: 100
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 300
server:
  port: 8883
#  context-path: /nercms


